### ISSUE TITLE
nx30pro的固件怎么刷？能出一个bin格式的固件么？

### ISSUE THREAD

**Issue by chenyuyou** [XiaoBinin/Actions-immortalwrt#1]

**Comment by XiaoBinin** [comment]
releases里面有编译好的。具体怎么刷论坛有教程

**Comment by chenyuyou** [comment]
> releases里面有编译好的。具体怎么刷论坛有教程

我已经到处找了，都是刷bin的，包括恩山的

**Comment by XiaoBinin** [comment]
> > releases里面有编译好的。具体怎么刷论坛有教程
> 
> 我已经到处找了，都是刷bin的，包括恩山的

uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。

**Comment by chenyuyou** [comment]
> > > releases里面有编译好的。具体怎么刷论坛有教程
> > 
> > 
> > 我已经到处找了，都是刷bin的，包括恩山的
> 
> uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。

我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7
但是这个uboot刷不进你编译的固件，搞不懂为什么

**Comment by XiaoBinin** [comment]
> > > > releases里面有编译好的。具体怎么刷论坛有教程
> > > 
> > > 
> > > 我已经到处找了，都是刷bin的，包括恩山的
> > 
> > 
> > uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。
> 
> 我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7 但是这个uboot刷不进你编译的固件，搞不懂为什么

改好了，现在可以去下载了

**Comment by chenyuyou** [comment]
> > > > > releases里面有编译好的。具体怎么刷论坛有教程
> > > > 
> > > > 
> > > > 我已经到处找了，都是刷bin的，包括恩山的
> > > 
> > > 
> > > uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。
> > 
> > 
> > 我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7 但是这个uboot刷不进你编译的固件，搞不懂为什么
> 
> 改好了，现在可以去下载了

我测过了，用不了，不知道什么原因。我测过 Bleach OpenWrt 的nx30 pro固件和lean 制作的潘多拉固件，都是能用。

**Comment by XiaoBinin** [comment]
> > > > > > releases里面有编译好的。具体怎么刷论坛有教程
> > > > > 
> > > > > 
> > > > > 我已经到处找了，都是刷bin的，包括恩山的
> > > > 
> > > > 
> > > > uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。
> > > 
> > > 
> > > 我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7 但是这个uboot刷不进你编译的固件，搞不懂为什么
> > 
> > 
> > 改好了，现在可以去下载了
> 
> 我测过了，用不了，不知道什么原因。我测过 Bleach OpenWrt 的nx30 pro固件和lean 制作的潘多拉固件，都是能用。

刷的是h3c_magic-nx30-pro-nmbm-squashfs-sysupgrade.bin 这个吗？
如果sysupgrade刷不进再尝试h3c_magic-nx30-pro-nmbm-squashfs-factory.bin

**Comment by chenyuyou** [comment]
> > > > > > > releases里面有编译好的。具体怎么刷论坛有教程
> > > > > > 
> > > > > > 
> > > > > > 我已经到处找了，都是刷bin的，包括恩山的
> > > > > 
> > > > > 
> > > > > uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。
> > > > 
> > > > 
> > > > 我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7 但是这个uboot刷不进你编译的固件，搞不懂为什么
> > > 
> > > 
> > > 改好了，现在可以去下载了
> > 
> > 
> > 我测过了，用不了，不知道什么原因。我测过 Bleach OpenWrt 的nx30 pro固件和lean 制作的潘多拉固件，都是能用。
> 
> 刷的是h3c_magic-nx30-pro-nmbm-squashfs-sysupgrade.bin 这个吗？ 如果sysupgrade刷不进再尝试h3c_magic-nx30-pro-nmbm-squashfs-factory.bin

我刷了3个文件kernel、sysupgrade和factory，都不行。挺奇怪。
之前的xunlong_orangepi-r1-plus-lts固件很好用，体质不好的软路由也能运行。但是最近修改后，wan口貌似用不了了

**Comment by XiaoBinin** [comment]
> > > > > > > > releases里面有编译好的。具体怎么刷论坛有教程
> > > > > > > 
> > > > > > > 
> > > > > > > 我已经到处找了，都是刷bin的，包括恩山的
> > > > > > 
> > > > > > 
> > > > > > uboot刷了吗？我这个编译的源码来自天灵的代码不是那个大分区的。
> > > > > 
> > > > > 
> > > > > 我刷了uboot，来自这个网站https://p.xiaowansm.repl.co/OneDrive/%f0%9f%94%a5OpenWrt_LEAN/H3C%20NX30Pro/%e5%88%b7%e6%9c%ba%e5%b7%a5%e5%85%b7 但是这个uboot刷不进你编译的固件，搞不懂为什么
> > > > 
> > > > 
> > > > 改好了，现在可以去下载了
> > > 
> > > 
> > > 我测过了，用不了，不知道什么原因。我测过 Bleach OpenWrt 的nx30 pro固件和lean 制作的潘多拉固件，都是能用。
> > 
> > 
> > 刷的是h3c_magic-nx30-pro-nmbm-squashfs-sysupgrade.bin 这个吗？ 如果sysupgrade刷不进再尝试h3c_magic-nx30-pro-nmbm-squashfs-factory.bin
> 
> 我刷了3个文件kernel、sysupgrade和factory，都不行。挺奇怪。 之前的xunlong_orangepi-r1-plus-lts固件很好用，体质不好的软路由也能运行。但是最近修改后，wan口貌似用不了了

r1-plus-lts用天灵21.02的那个版本，23.05那个版本跟wan口驱动有兼容性问题，等天灵大佬修。隔壁lede的没问题，5.4内核。
nx30-pro还是不行的话，直接尝试天灵那个固件生成网址看看能否正常使用。链接：https://firmware-selector.immortalwrt.org/
